######################################################################
##
## Filename: s6base_tb.udo
## Created on: Sat Jan 04 00:27:35 GMT Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
